import jsPDF from 'jspdf';
import { format } from 'date-fns';

interface ChecklistItem {
  id: string;
  category: string;
  item: string;
  requirement: string;
  checked: boolean;
  notes: string;
  status: 'pending' | 'pass' | 'fail' | 'na';
}

interface ChecklistFormData {
  projectName: string;
  projectAddress: string;
  inspectionType: string;
  inspectorName: string;
  permitNumber: string;
  inspectionDate: string;
  weather?: string;
  temperature?: string;
  generalNotes: string;
}

interface SavedChecklist {
  id: string;
  name: string;
  form_data: ChecklistFormData;
  checklist_items: ChecklistItem[];
  custom_items: ChecklistItem[];
  inspector_signed_at: string | null;
  contractor_signed_at: string | null;
  status: string;
  created_at: string;
  updated_at: string;
}

const INSPECTION_TYPE_LABELS: Record<string, string> = {
  foundation: 'Foundation',
  framing: 'Framing',
  electrical_rough: 'Electrical Rough',
  electrical_final: 'Electrical Final',
  plumbing_rough: 'Plumbing Rough',
  plumbing_final: 'Plumbing Final',
  mechanical_rough: 'Mechanical Rough',
  mechanical_final: 'Mechanical Final',
  insulation: 'Insulation',
  drywall: 'Drywall',
  fire_safety: 'Fire Safety',
  final: 'Final',
  other: 'Other',
};

const STATUS_COLORS: Record<string, [number, number, number]> = {
  pass: [22, 163, 74],
  fail: [220, 38, 38],
  na: [113, 113, 122],
  pending: [202, 138, 4],
};

function getInspectionTypeLabel(type: string): string {
  return INSPECTION_TYPE_LABELS[type] || type;
}

export function downloadCombinedChecklistPDF(
  checklists: SavedChecklist[],
  projectName: string
) {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  const drawHorizontalLine = (y: number, color: [number, number, number] = [226, 232, 240]) => {
    pdf.setDrawColor(...color);
    pdf.setLineWidth(0.3);
    pdf.line(margin, y, pageWidth - margin, y);
  };

  const addFooter = (pageNum: number, totalPages: number) => {
    const footerY = pageHeight - 10;
    pdf.setTextColor(148, 163, 184);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Page ${pageNum} of ${totalPages}`, pageWidth / 2, footerY, { align: 'center' });
    pdf.text('Generated by PermitFlow', pageWidth / 2, footerY + 4, { align: 'center' });
  };

  // ===== COVER PAGE =====
  let yPos = margin;

  // Header
  pdf.setFillColor(30, 41, 59);
  pdf.rect(0, 0, pageWidth, 50, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(24);
  pdf.text('Inspection Checklists Report', margin, 25);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(12);
  pdf.text(projectName || 'All Projects', margin, 38);

  yPos = 65;

  // Report info
  pdf.setTextColor(30, 41, 59);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.text('Report Summary', margin, yPos);
  yPos += 3;
  drawHorizontalLine(yPos);
  yPos += 10;

  pdf.setFontSize(10);
  const reportDetails = [
    ['Generated:', format(new Date(), 'MMMM d, yyyy h:mm a')],
    ['Total Checklists:', checklists.length.toString()],
    ['Project:', projectName || 'All Projects'],
  ];

  reportDetails.forEach(([label, value]) => {
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 116, 139);
    pdf.text(label, margin, yPos);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(30, 41, 59);
    pdf.text(value, margin + 45, yPos);
    yPos += 7;
  });

  yPos += 10;

  // Overall summary statistics
  const allItems = checklists.flatMap(c => [...c.checklist_items, ...c.custom_items]);
  const overallSummary = {
    total: allItems.length,
    passed: allItems.filter(i => i.status === 'pass').length,
    failed: allItems.filter(i => i.status === 'fail').length,
    pending: allItems.filter(i => i.status === 'pending').length,
    na: allItems.filter(i => i.status === 'na').length,
  };

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.text('Overall Statistics', margin, yPos);
  yPos += 3;
  drawHorizontalLine(yPos);
  yPos += 10;

  const summaryBoxWidth = (contentWidth - 15) / 4;
  const summaryBoxHeight = 22;
  const summaryItems = [
    { label: 'PASSED', value: overallSummary.passed, color: [240, 253, 244] as [number, number, number], textColor: [22, 163, 74] as [number, number, number] },
    { label: 'FAILED', value: overallSummary.failed, color: [254, 242, 242] as [number, number, number], textColor: [220, 38, 38] as [number, number, number] },
    { label: 'PENDING', value: overallSummary.pending, color: [254, 252, 232] as [number, number, number], textColor: [202, 138, 4] as [number, number, number] },
    { label: 'N/A', value: overallSummary.na, color: [244, 244, 245] as [number, number, number], textColor: [113, 113, 122] as [number, number, number] },
  ];

  summaryItems.forEach((item, index) => {
    const x = margin + index * (summaryBoxWidth + 5);
    pdf.setFillColor(...item.color);
    pdf.roundedRect(x, yPos, summaryBoxWidth, summaryBoxHeight, 2, 2, 'F');

    pdf.setTextColor(...item.textColor);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(18);
    pdf.text(item.value.toString(), x + summaryBoxWidth / 2, yPos + 12, { align: 'center' });

    pdf.setFontSize(8);
    pdf.text(item.label, x + summaryBoxWidth / 2, yPos + 18, { align: 'center' });
  });

  yPos += summaryBoxHeight + 10;
  pdf.setTextColor(100, 116, 139);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.text(`Total Inspection Items: ${overallSummary.total}`, pageWidth / 2, yPos, { align: 'center' });

  yPos += 20;

  // Table of contents
  pdf.setTextColor(30, 41, 59);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.text('Checklists Included', margin, yPos);
  yPos += 3;
  drawHorizontalLine(yPos);
  yPos += 8;

  pdf.setFontSize(10);
  checklists.forEach((checklist, index) => {
    if (yPos > pageHeight - 30) {
      pdf.addPage();
      yPos = margin;
    }

    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(30, 41, 59);
    pdf.text(`${index + 1}. ${checklist.name}`, margin, yPos);

    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 116, 139);
    const details = `${getInspectionTypeLabel(checklist.form_data.inspectionType)} - ${format(new Date(checklist.updated_at), 'MMM d, yyyy')}`;
    pdf.text(details, margin + 5, yPos + 5);

    yPos += 12;
  });

  // Add individual checklists
  checklists.forEach((checklist, checklistIndex) => {
    pdf.addPage();
    yPos = margin;

    const allChecklistItems = [...checklist.checklist_items, ...checklist.custom_items];
    const summary = {
      total: allChecklistItems.length,
      passed: allChecklistItems.filter(i => i.status === 'pass').length,
      failed: allChecklistItems.filter(i => i.status === 'fail').length,
      pending: allChecklistItems.filter(i => i.status === 'pending').length,
      na: allChecklistItems.filter(i => i.status === 'na').length,
    };

    // Determine overall status
    let overallStatus = 'PASSED';
    let statusColor: [number, number, number] = [22, 163, 74];
    if (summary.failed > 0) {
      overallStatus = 'FAILED - Corrections Required';
      statusColor = [220, 38, 38];
    } else if (summary.pending > 0) {
      overallStatus = 'INCOMPLETE - Items Pending';
      statusColor = [202, 138, 4];
    }

    // Checklist header
    pdf.setFillColor(30, 41, 59);
    pdf.rect(0, 0, pageWidth, 35, 'F');

    pdf.setTextColor(255, 255, 255);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(16);
    pdf.text(`Checklist ${checklistIndex + 1}: ${checklist.name}`, margin, 18);

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(10);
    pdf.text(getInspectionTypeLabel(checklist.form_data.inspectionType), margin, 28);

    yPos = 45;

    // Status banner
    pdf.setFillColor(...statusColor);
    pdf.rect(margin, yPos, contentWidth, 10, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(10);
    pdf.text(overallStatus, pageWidth / 2, yPos + 7, { align: 'center' });

    yPos += 18;

    // Project details
    pdf.setTextColor(30, 41, 59);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.text('Project Details', margin, yPos);
    yPos += 3;
    drawHorizontalLine(yPos);
    yPos += 7;

    pdf.setFontSize(9);
    const projectDetails = [
      ['Project:', checklist.form_data.projectName || 'N/A'],
      ['Address:', checklist.form_data.projectAddress || 'N/A'],
      ['Permit #:', checklist.form_data.permitNumber || 'N/A'],
      ['Inspector:', checklist.form_data.inspectorName || 'N/A'],
      ['Date:', checklist.form_data.inspectionDate || 'N/A'],
    ];

    projectDetails.forEach(([label, value]) => {
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(100, 116, 139);
      pdf.text(label, margin, yPos);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(30, 41, 59);
      pdf.text(value, margin + 25, yPos);
      yPos += 5;
    });

    yPos += 8;

    // Summary boxes
    const smallBoxWidth = (contentWidth - 15) / 4;
    const smallBoxHeight = 16;
    const smallSummaryItems = [
      { label: 'PASS', value: summary.passed, color: [240, 253, 244] as [number, number, number], textColor: [22, 163, 74] as [number, number, number] },
      { label: 'FAIL', value: summary.failed, color: [254, 242, 242] as [number, number, number], textColor: [220, 38, 38] as [number, number, number] },
      { label: 'PENDING', value: summary.pending, color: [254, 252, 232] as [number, number, number], textColor: [202, 138, 4] as [number, number, number] },
      { label: 'N/A', value: summary.na, color: [244, 244, 245] as [number, number, number], textColor: [113, 113, 122] as [number, number, number] },
    ];

    smallSummaryItems.forEach((item, index) => {
      const x = margin + index * (smallBoxWidth + 5);
      pdf.setFillColor(...item.color);
      pdf.roundedRect(x, yPos, smallBoxWidth, smallBoxHeight, 2, 2, 'F');

      pdf.setTextColor(...item.textColor);
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(12);
      pdf.text(item.value.toString(), x + smallBoxWidth / 2, yPos + 8, { align: 'center' });

      pdf.setFontSize(7);
      pdf.text(item.label, x + smallBoxWidth / 2, yPos + 13, { align: 'center' });
    });

    yPos += smallBoxHeight + 10;

    // Checklist items by category
    const itemsByCategory = allChecklistItems.reduce((acc, item) => {
      const cat = item.category || 'Other';
      if (!acc[cat]) acc[cat] = [];
      acc[cat].push(item);
      return acc;
    }, {} as Record<string, ChecklistItem[]>);

    Object.entries(itemsByCategory).forEach(([category, items]) => {
      if (yPos > pageHeight - 30) {
        pdf.addPage();
        yPos = margin;
      }

      pdf.setTextColor(30, 41, 59);
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(10);
      pdf.text(category, margin, yPos);
      yPos += 3;
      drawHorizontalLine(yPos);
      yPos += 5;

      items.forEach(item => {
        if (yPos > pageHeight - 25) {
          pdf.addPage();
          yPos = margin;
        }

        // Status badge
        const [r, g, b] = STATUS_COLORS[item.status];
        pdf.setFillColor(r, g, b);
        pdf.roundedRect(margin, yPos - 3, 14, 4, 1, 1, 'F');
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(5);
        pdf.setFont('helvetica', 'bold');
        pdf.text(item.status.toUpperCase(), margin + 7, yPos - 0.5, { align: 'center' });

        // Item text
        pdf.setTextColor(30, 41, 59);
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(8);
        const itemText = pdf.splitTextToSize(item.item, contentWidth - 20);
        pdf.text(itemText, margin + 18, yPos);
        yPos += itemText.length * 3 + 3;
      });

      yPos += 3;
    });

    // Notes
    if (checklist.form_data.generalNotes) {
      if (yPos > pageHeight - 40) {
        pdf.addPage();
        yPos = margin;
      }

      pdf.setTextColor(30, 41, 59);
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(10);
      pdf.text('Notes', margin, yPos);
      yPos += 3;
      drawHorizontalLine(yPos);
      yPos += 6;

      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(8);
      pdf.setTextColor(51, 65, 85);
      const notesLines = pdf.splitTextToSize(checklist.form_data.generalNotes, contentWidth);
      pdf.text(notesLines, margin, yPos);
      yPos += notesLines.length * 3.5 + 5;
    }

    // Signatures
    if (yPos > pageHeight - 35) {
      pdf.addPage();
      yPos = margin;
    }

    pdf.setTextColor(30, 41, 59);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(10);
    pdf.text('Signatures', margin, yPos);
    yPos += 3;
    drawHorizontalLine(yPos);
    yPos += 6;

    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 116, 139);
    pdf.text(`Inspector: ${checklist.inspector_signed_at ? format(new Date(checklist.inspector_signed_at), 'MMM d, yyyy h:mm a') : 'Not signed'}`, margin, yPos);
    pdf.text(`Contractor: ${checklist.contractor_signed_at ? format(new Date(checklist.contractor_signed_at), 'MMM d, yyyy h:mm a') : 'Not signed'}`, margin + contentWidth / 2, yPos);
  });

  // Add page numbers
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    addFooter(i, totalPages);
  }

  // Download
  const filename = `inspection-report-${projectName ? projectName.replace(/[^a-z0-9]/gi, '-').toLowerCase() : 'all-projects'}-${format(new Date(), 'yyyy-MM-dd')}.pdf`;
  pdf.save(filename);
}

export function generateCombinedChecklistPDFBase64(
  checklists: SavedChecklist[],
  projectName: string
): { base64: string; fileName: string } {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  const drawHorizontalLine = (y: number, color: [number, number, number] = [226, 232, 240]) => {
    pdf.setDrawColor(...color);
    pdf.setLineWidth(0.3);
    pdf.line(margin, y, pageWidth - margin, y);
  };

  const addFooter = (pageNum: number, totalPages: number) => {
    const footerY = pageHeight - 10;
    pdf.setTextColor(148, 163, 184);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Page ${pageNum} of ${totalPages}`, pageWidth / 2, footerY, { align: 'center' });
    pdf.text('Generated by PermitFlow', pageWidth / 2, footerY + 4, { align: 'center' });
  };

  // ===== COVER PAGE =====
  let yPos = margin;

  // Header
  pdf.setFillColor(30, 41, 59);
  pdf.rect(0, 0, pageWidth, 50, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(24);
  pdf.text('Inspection Checklists Report', margin, 25);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(12);
  pdf.text(projectName || 'All Projects', margin, 38);

  yPos = 65;

  // Report info
  pdf.setTextColor(30, 41, 59);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.text('Report Summary', margin, yPos);
  yPos += 3;
  drawHorizontalLine(yPos);
  yPos += 10;

  pdf.setFontSize(10);
  const reportDetails = [
    ['Generated:', format(new Date(), 'MMMM d, yyyy h:mm a')],
    ['Total Checklists:', checklists.length.toString()],
    ['Project:', projectName || 'All Projects'],
  ];

  reportDetails.forEach(([label, value]) => {
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 116, 139);
    pdf.text(label, margin, yPos);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(30, 41, 59);
    pdf.text(value, margin + 45, yPos);
    yPos += 7;
  });

  yPos += 10;

  // Overall summary statistics
  const allItems = checklists.flatMap(c => [...c.checklist_items, ...c.custom_items]);
  const overallSummary = {
    total: allItems.length,
    passed: allItems.filter(i => i.status === 'pass').length,
    failed: allItems.filter(i => i.status === 'fail').length,
    pending: allItems.filter(i => i.status === 'pending').length,
    na: allItems.filter(i => i.status === 'na').length,
  };

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.text('Overall Statistics', margin, yPos);
  yPos += 3;
  drawHorizontalLine(yPos);
  yPos += 10;

  const summaryBoxWidth = (contentWidth - 15) / 4;
  const summaryBoxHeight = 22;
  const summaryItems = [
    { label: 'PASSED', value: overallSummary.passed, color: [240, 253, 244] as [number, number, number], textColor: [22, 163, 74] as [number, number, number] },
    { label: 'FAILED', value: overallSummary.failed, color: [254, 242, 242] as [number, number, number], textColor: [220, 38, 38] as [number, number, number] },
    { label: 'PENDING', value: overallSummary.pending, color: [254, 252, 232] as [number, number, number], textColor: [202, 138, 4] as [number, number, number] },
    { label: 'N/A', value: overallSummary.na, color: [244, 244, 245] as [number, number, number], textColor: [113, 113, 122] as [number, number, number] },
  ];

  summaryItems.forEach((item, index) => {
    const x = margin + index * (summaryBoxWidth + 5);
    pdf.setFillColor(...item.color);
    pdf.roundedRect(x, yPos, summaryBoxWidth, summaryBoxHeight, 2, 2, 'F');

    pdf.setTextColor(...item.textColor);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(18);
    pdf.text(item.value.toString(), x + summaryBoxWidth / 2, yPos + 12, { align: 'center' });

    pdf.setFontSize(8);
    pdf.text(item.label, x + summaryBoxWidth / 2, yPos + 18, { align: 'center' });
  });

  yPos += summaryBoxHeight + 10;
  pdf.setTextColor(100, 116, 139);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.text(`Total Inspection Items: ${overallSummary.total}`, pageWidth / 2, yPos, { align: 'center' });

  yPos += 20;

  // Table of contents
  pdf.setTextColor(30, 41, 59);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.text('Checklists Included', margin, yPos);
  yPos += 3;
  drawHorizontalLine(yPos);
  yPos += 8;

  pdf.setFontSize(10);
  checklists.forEach((checklist, index) => {
    if (yPos > pageHeight - 30) {
      pdf.addPage();
      yPos = margin;
    }

    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(30, 41, 59);
    pdf.text(`${index + 1}. ${checklist.name}`, margin, yPos);

    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 116, 139);
    const details = `${getInspectionTypeLabel(checklist.form_data.inspectionType)} - ${format(new Date(checklist.updated_at), 'MMM d, yyyy')}`;
    pdf.text(details, margin + 5, yPos + 5);

    yPos += 12;
  });

  // Add individual checklists (abbreviated version for email)
  checklists.forEach((checklist, checklistIndex) => {
    pdf.addPage();
    yPos = margin;

    const allChecklistItems = [...checklist.checklist_items, ...checklist.custom_items];
    const summary = {
      total: allChecklistItems.length,
      passed: allChecklistItems.filter(i => i.status === 'pass').length,
      failed: allChecklistItems.filter(i => i.status === 'fail').length,
      pending: allChecklistItems.filter(i => i.status === 'pending').length,
      na: allChecklistItems.filter(i => i.status === 'na').length,
    };

    let overallStatus = 'PASSED';
    let statusColor: [number, number, number] = [22, 163, 74];
    if (summary.failed > 0) {
      overallStatus = 'FAILED - Corrections Required';
      statusColor = [220, 38, 38];
    } else if (summary.pending > 0) {
      overallStatus = 'INCOMPLETE - Items Pending';
      statusColor = [202, 138, 4];
    }

    pdf.setFillColor(30, 41, 59);
    pdf.rect(0, 0, pageWidth, 35, 'F');

    pdf.setTextColor(255, 255, 255);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(16);
    pdf.text(`Checklist ${checklistIndex + 1}: ${checklist.name}`, margin, 18);

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(10);
    pdf.text(getInspectionTypeLabel(checklist.form_data.inspectionType), margin, 28);

    yPos = 45;

    pdf.setFillColor(...statusColor);
    pdf.rect(margin, yPos, contentWidth, 10, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(10);
    pdf.text(overallStatus, pageWidth / 2, yPos + 7, { align: 'center' });

    yPos += 18;

    pdf.setTextColor(30, 41, 59);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.text('Project Details', margin, yPos);
    yPos += 3;
    drawHorizontalLine(yPos);
    yPos += 7;

    pdf.setFontSize(9);
    const projectDetails = [
      ['Project:', checklist.form_data.projectName || 'N/A'],
      ['Address:', checklist.form_data.projectAddress || 'N/A'],
      ['Permit #:', checklist.form_data.permitNumber || 'N/A'],
      ['Inspector:', checklist.form_data.inspectorName || 'N/A'],
      ['Date:', checklist.form_data.inspectionDate || 'N/A'],
    ];

    projectDetails.forEach(([label, value]) => {
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(100, 116, 139);
      pdf.text(label, margin, yPos);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(30, 41, 59);
      pdf.text(value, margin + 25, yPos);
      yPos += 5;
    });

    yPos += 8;

    const smallBoxWidth = (contentWidth - 15) / 4;
    const smallBoxHeight = 16;
    const smallSummaryItems = [
      { label: 'PASS', value: summary.passed, color: [240, 253, 244] as [number, number, number], textColor: [22, 163, 74] as [number, number, number] },
      { label: 'FAIL', value: summary.failed, color: [254, 242, 242] as [number, number, number], textColor: [220, 38, 38] as [number, number, number] },
      { label: 'PENDING', value: summary.pending, color: [254, 252, 232] as [number, number, number], textColor: [202, 138, 4] as [number, number, number] },
      { label: 'N/A', value: summary.na, color: [244, 244, 245] as [number, number, number], textColor: [113, 113, 122] as [number, number, number] },
    ];

    smallSummaryItems.forEach((item, index) => {
      const x = margin + index * (smallBoxWidth + 5);
      pdf.setFillColor(...item.color);
      pdf.roundedRect(x, yPos, smallBoxWidth, smallBoxHeight, 2, 2, 'F');

      pdf.setTextColor(...item.textColor);
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(12);
      pdf.text(item.value.toString(), x + smallBoxWidth / 2, yPos + 8, { align: 'center' });

      pdf.setFontSize(7);
      pdf.text(item.label, x + smallBoxWidth / 2, yPos + 13, { align: 'center' });
    });
  });

  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    addFooter(i, totalPages);
  }

  const fileName = `inspection-report-${projectName ? projectName.replace(/[^a-z0-9]/gi, '-').toLowerCase() : 'all-projects'}-${format(new Date(), 'yyyy-MM-dd')}.pdf`;
  const base64 = pdf.output('datauristring').split(',')[1];

  return { base64, fileName };
}
