import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface ScheduledReport {
  id: string;
  user_id: string;
  name: string;
  recipient_email: string;
  recipient_name: string | null;
  project_filter: string;
  status_filter: string;
  frequency: string;
  timezone: string;
  send_time: string;
  email_subject: string | null;
  email_intro: string | null;
  include_summary: boolean;
  include_details: boolean;
  include_pdf_attachment: boolean;
}

interface ChecklistItem {
  id: string;
  category: string;
  item: string;
  status: string;
}

interface SavedChecklist {
  id: string;
  name: string;
  status: string;
  form_data: {
    projectName: string;
    inspectionType: string;
  };
  checklist_items: ChecklistItem[];
  custom_items: ChecklistItem[];
  updated_at: string;
}

interface BrandingSettings {
  logo_url: string | null;
  primary_color: string;
  header_text: string;
  footer_text: string;
  unsubscribe_text: string;
}

const DEFAULT_BRANDING: BrandingSettings = {
  logo_url: null,
  primary_color: "#0f4c5c",
  header_text: "Inspection Report",
  footer_text: "Best regards,\nThe Insight|DesignCheck Team",
  unsubscribe_text: "This is an automated report. To manage your scheduled reports, visit your dashboard.",
};

// Helper to adjust color for gradient
function adjustColor(hex: string, amount: number): string {
  const clamp = (num: number) => Math.min(255, Math.max(0, num));
  const color = hex.replace("#", "");
  const num = parseInt(color, 16);
  const r = clamp((num >> 16) + amount);
  const g = clamp(((num >> 8) & 0x00ff) + amount);
  const b = clamp((num & 0x0000ff) + amount);
  return `#${((r << 16) | (g << 8) | b).toString(16).padStart(6, "0")}`;
}

// Generate a simple text-based PDF report using base64 encoding
function generatePDFReport(
  checklists: SavedChecklist[],
  projectName: string,
  reportName: string,
  summary: { total: number; passed: number; failed: number; pending: number }
): string {
  // Build PDF content as a formatted text document
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  let content = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
4 0 obj
<< /Length 6 0 R >>
stream
BT
/F1 24 Tf
50 740 Td
(Inspection Checklists Report) Tj
/F1 12 Tf
0 -30 Td
(Report: ${reportName.replace(/[()\\]/g, '')}) Tj
0 -20 Td
(Project: ${projectName.replace(/[()\\]/g, '')}) Tj
0 -20 Td
(Generated: ${dateStr}) Tj
0 -40 Td
/F1 16 Tf
(Summary) Tj
/F1 12 Tf
0 -25 Td
(Total Checklists: ${summary.total}) Tj
0 -18 Td
(Passed Items: ${summary.passed}) Tj
0 -18 Td
(Failed Items: ${summary.failed}) Tj
0 -18 Td
(Pending Items: ${summary.pending}) Tj
0 -40 Td
/F1 16 Tf
(Checklists Included) Tj
/F1 11 Tf
`;

  let yOffset = 0;
  const maxChecklists = Math.min(checklists.length, 15);
  
  for (let i = 0; i < maxChecklists; i++) {
    const c = checklists[i];
    const name = (c.name || 'Unnamed').replace(/[()\\]/g, '').substring(0, 50);
    const type = (c.form_data?.inspectionType || 'N/A').replace(/[()\\]/g, '');
    const status = (c.status || 'unknown').toUpperCase();
    
    content += `0 -20 Td
(${i + 1}. ${name} - ${type} [${status}]) Tj
`;
    yOffset += 20;
  }

  if (checklists.length > maxChecklists) {
    content += `0 -20 Td
(... and ${checklists.length - maxChecklists} more checklists) Tj
`;
  }

  content += `0 -40 Td
/F1 10 Tf
(Generated by Insight|DesignCheck) Tj
ET
endstream
endobj
6 0 obj
${content.split('stream\n')[1].split('\nendstream')[0].length}
endobj
xref
0 7
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000270 00000 n 
0000000214 00000 n 
trailer
<< /Size 7 /Root 1 0 R >>
startxref
%%EOF`;

  // Encode to base64
  const encoder = new TextEncoder();
  const data = encoder.encode(content);
  let binary = '';
  for (let i = 0; i < data.length; i++) {
    binary += String.fromCharCode(data[i]);
  }
  return btoa(binary);
}

const handler = async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const now = new Date();

    console.log(`Processing scheduled checklist reports at ${now.toISOString()}`);

    // Fetch branding settings
    const { data: brandingData } = await supabase
      .from("email_branding_settings")
      .select("*")
      .limit(1)
      .single();

    const branding: BrandingSettings = brandingData || DEFAULT_BRANDING;
    console.log("Using branding settings:", branding.header_text);

    // Get all active scheduled reports that are due
    const { data: dueReports, error: fetchError } = await supabase
      .from("scheduled_checklist_reports")
      .select("*")
      .eq("is_active", true)
      .lte("next_send_at", now.toISOString());

    if (fetchError) {
      console.error("Error fetching scheduled reports:", fetchError);
      throw fetchError;
    }

    if (!dueReports || dueReports.length === 0) {
      console.log("No scheduled reports due");
      return new Response(
        JSON.stringify({ message: "No reports due", processed: 0 }),
        { status: 200, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    console.log(`Found ${dueReports.length} reports due`);

    let processedCount = 0;
    let errorCount = 0;

    for (const report of dueReports as ScheduledReport[]) {
      try {
        // Fetch user's checklists based on filters
        let query = supabase
          .from("saved_inspection_checklists")
          .select("*")
          .eq("user_id", report.user_id)
          .order("updated_at", { ascending: false });

        if (report.status_filter && report.status_filter !== "all") {
          query = query.eq("status", report.status_filter);
        }

        const { data: checklists, error: checklistError } = await query;

        if (checklistError) {
          console.error(`Error fetching checklists for report ${report.id}:`, checklistError);
          errorCount++;
          continue;
        }

        // Filter by project if needed
        let filteredChecklists = checklists || [];
        if (report.project_filter && report.project_filter !== "all") {
          filteredChecklists = filteredChecklists.filter(
            (c: SavedChecklist) => c.form_data?.projectName === report.project_filter
          );
        }

        if (filteredChecklists.length === 0) {
          console.log(`No checklists found for report ${report.id}, skipping`);
          // Still update next_send_at
          await updateNextSendTime(supabase, report);
          continue;
        }

        // Generate summary statistics
        const allItems = filteredChecklists.flatMap((c: SavedChecklist) => [
          ...(c.checklist_items || []),
          ...(c.custom_items || []),
        ]);

        const summary = {
          total: filteredChecklists.length,
          passed: allItems.filter((i: ChecklistItem) => i.status === "pass").length,
          failed: allItems.filter((i: ChecklistItem) => i.status === "fail").length,
          pending: allItems.filter((i: ChecklistItem) => i.status === "pending").length,
        };

        // Build email HTML with branding
        const projectName = report.project_filter !== "all" ? report.project_filter : "All Projects";
        const emailSubject = report.email_subject || `${report.frequency === "weekly" ? "Weekly" : "Monthly"} Inspection Report - ${projectName}`;
        const emailIntro = report.email_intro || `Here is your ${report.frequency} inspection checklists report.`;

        const emailHtml = buildEmailHtml(
          report.recipient_name || "",
          projectName,
          emailIntro,
          filteredChecklists,
          summary,
          report.include_summary,
          report.include_details,
          branding
        );

        // Parse multiple recipients (comma-separated)
        const recipientEmails = report.recipient_email
          .split(',')
          .map((e: string) => e.trim())
          .filter((e: string) => e.length > 0 && e.includes('@'));

        const recipientNames = (report.recipient_name || '')
          .split(',')
          .map((n: string) => n.trim());

        console.log(`Sending report ${report.id} to ${recipientEmails.length} recipient(s), PDF attachment: ${report.include_pdf_attachment}`);

        // Generate PDF if attachment is enabled
        let pdfBase64: string | null = null;
        if (report.include_pdf_attachment && filteredChecklists.length > 0) {
          pdfBase64 = generatePDFReport(filteredChecklists, projectName, report.name, summary);
          console.log(`Generated PDF attachment for report ${report.id}`);
        }

        // Send to all recipients in parallel
        const emailPromises = recipientEmails.map(async (email: string, index: number) => {
          const recipientName = recipientNames[index] || '';
          const personalizedHtml = buildEmailHtml(
            recipientName,
            projectName,
            emailIntro,
            filteredChecklists,
            summary,
            report.include_summary,
            report.include_details,
            branding
          );

          const emailPayload: any = {
            from: "Insight|DesignCheck <onboarding@resend.dev>",
            to: [email],
            subject: emailSubject,
            html: personalizedHtml,
          };

          // Add PDF attachment if enabled
          if (pdfBase64) {
            emailPayload.attachments = [
              {
                filename: `inspection-report-${projectName.replace(/[^a-zA-Z0-9]/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf`,
                content: pdfBase64,
              },
            ];
          }

          const emailRes = await fetch("https://api.resend.com/emails", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${RESEND_API_KEY}`,
            },
            body: JSON.stringify(emailPayload),
          });

          if (!emailRes.ok) {
            const errorData = await emailRes.json();
            console.error(`Failed to send email to ${email}:`, errorData);
            return { success: false, email };
          }

          console.log(`Successfully sent report to ${email}`);
          return { success: true, email };
        });

        const results = await Promise.all(emailPromises);
        const failedEmails = results.filter(r => !r.success);
        const successfulEmails = results.filter(r => r.success);

        // Determine overall status
        let deliveryStatus = 'success';
        if (failedEmails.length === recipientEmails.length) {
          deliveryStatus = 'failed';
        } else if (failedEmails.length > 0) {
          deliveryStatus = 'partial';
        }

        // Log delivery to history
        const { error: logError } = await supabase
          .from('scheduled_report_delivery_logs')
          .insert({
            report_id: report.id,
            user_id: report.user_id,
            report_name: report.name,
            recipient_emails: recipientEmails,
            recipient_count: recipientEmails.length,
            successful_count: successfulEmails.length,
            failed_count: failedEmails.length,
            failed_emails: failedEmails.map(f => f.email),
            status: deliveryStatus,
            error_message: failedEmails.length > 0 ? `Failed to send to: ${failedEmails.map(f => f.email).join(', ')}` : null,
            sent_at: new Date().toISOString(),
          });

        if (logError) {
          console.error(`Failed to log delivery for report ${report.id}:`, logError);
        }

        if (failedEmails.length === recipientEmails.length) {
          // All failed
          console.error(`All emails failed for report ${report.id}`);
          errorCount++;
          continue;
        }

        if (failedEmails.length > 0) {
          console.warn(`Some emails failed for report ${report.id}:`, failedEmails.map(f => f.email));
        }

        console.log(`Successfully sent report ${report.id} to ${recipientEmails.length - failedEmails.length}/${recipientEmails.length} recipients`);

        // Update last_sent_at and next_send_at
        await updateNextSendTime(supabase, report);
        processedCount++;
      } catch (err) {
        console.error(`Error processing report ${report.id}:`, err);
        errorCount++;
      }
    }

    return new Response(
      JSON.stringify({
        message: "Scheduled reports processed",
        processed: processedCount,
        errors: errorCount,
      }),
      { status: 200, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );
  } catch (error: any) {
    console.error("Error in process-scheduled-checklist-reports:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );
  }
};

async function updateNextSendTime(supabase: any, report: ScheduledReport) {
  const now = new Date();
  let nextSend = new Date();

  if (report.frequency === "weekly") {
    nextSend.setDate(nextSend.getDate() + 7);
  } else {
    nextSend.setMonth(nextSend.getMonth() + 1);
  }

  await supabase
    .from("scheduled_checklist_reports")
    .update({
      last_sent_at: now.toISOString(),
      next_send_at: nextSend.toISOString(),
    })
    .eq("id", report.id);
}

function buildEmailHtml(
  recipientName: string,
  projectName: string,
  intro: string,
  checklists: SavedChecklist[],
  summary: { total: number; passed: number; failed: number; pending: number },
  includeSummary: boolean,
  includeDetails: boolean,
  branding: BrandingSettings
): string {
  const greeting = recipientName ? `Hi ${recipientName},` : "Hi,";
  const primaryColor = branding.primary_color || "#0f4c5c";
  const gradientEnd = adjustColor(primaryColor, 30);
  const headerText = branding.header_text || "Inspection Report";
  const footerText = branding.footer_text || "Best regards,\nThe Insight|DesignCheck Team";
  const unsubscribeText = branding.unsubscribe_text || "This is an automated report. To manage your scheduled reports, visit your dashboard.";

  // Logo HTML
  const logoHtml = branding.logo_url
    ? `<img src="${branding.logo_url}" alt="Logo" style="max-height: 48px; margin-bottom: 16px;" />`
    : "";

  let summarySection = "";
  if (includeSummary) {
    summarySection = `
      <div style="background: #f1f5f9; padding: 20px; border-radius: 8px; margin: 24px 0;">
        <h3 style="margin: 0 0 16px 0; color: ${primaryColor};">Report Summary</h3>
        <div style="display: flex; gap: 16px; flex-wrap: wrap;">
          <div style="background: white; padding: 12px 20px; border-radius: 6px; text-align: center; flex: 1; min-width: 80px;">
            <div style="font-size: 24px; font-weight: bold; color: ${primaryColor};">${summary.total}</div>
            <div style="font-size: 12px; color: #64748b;">Checklists</div>
          </div>
          <div style="background: #dcfce7; padding: 12px 20px; border-radius: 6px; text-align: center; flex: 1; min-width: 80px;">
            <div style="font-size: 24px; font-weight: bold; color: #16a34a;">${summary.passed}</div>
            <div style="font-size: 12px; color: #16a34a;">Passed</div>
          </div>
          <div style="background: #fee2e2; padding: 12px 20px; border-radius: 6px; text-align: center; flex: 1; min-width: 80px;">
            <div style="font-size: 24px; font-weight: bold; color: #dc2626;">${summary.failed}</div>
            <div style="font-size: 12px; color: #dc2626;">Failed</div>
          </div>
          <div style="background: #fef3c7; padding: 12px 20px; border-radius: 6px; text-align: center; flex: 1; min-width: 80px;">
            <div style="font-size: 24px; font-weight: bold; color: #ca8a04;">${summary.pending}</div>
            <div style="font-size: 12px; color: #ca8a04;">Pending</div>
          </div>
        </div>
      </div>
    `;
  }

  let detailsSection = "";
  if (includeDetails && checklists.length > 0) {
    const checklistRows = checklists.slice(0, 10).map((c) => {
      const statusColor = c.status === "signed" ? "#16a34a" : c.status === "completed" ? "#2563eb" : "#ca8a04";
      return `
        <tr>
          <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">${c.name}</td>
          <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">${c.form_data?.inspectionType || "N/A"}</td>
          <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">
            <span style="background: ${statusColor}20; color: ${statusColor}; padding: 4px 8px; border-radius: 4px; font-size: 12px;">
              ${c.status}
            </span>
          </td>
        </tr>
      `;
    }).join("");

    detailsSection = `
      <div style="margin: 24px 0;">
        <h3 style="margin: 0 0 16px 0; color: ${primaryColor};">Recent Checklists</h3>
        <table style="width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden;">
          <thead>
            <tr style="background: #f8fafc;">
              <th style="padding: 12px; text-align: left; color: #64748b; font-weight: 600;">Name</th>
              <th style="padding: 12px; text-align: left; color: #64748b; font-weight: 600;">Type</th>
              <th style="padding: 12px; text-align: left; color: #64748b; font-weight: 600;">Status</th>
            </tr>
          </thead>
          <tbody>
            ${checklistRows}
          </tbody>
        </table>
        ${checklists.length > 10 ? `<p style="color: #64748b; font-size: 14px; margin-top: 12px;">... and ${checklists.length - 10} more checklists</p>` : ""}
      </div>
    `;
  }

  // Format footer text (convert newlines to <br>)
  const formattedFooter = footerText.replace(/\n/g, "<br>");

  return `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: linear-gradient(135deg, ${primaryColor} 0%, ${gradientEnd} 100%); padding: 32px; border-radius: 12px 12px 0 0;">
        ${logoHtml}
        <h1 style="color: white; margin: 0; font-size: 24px;">${headerText}</h1>
        <p style="color: rgba(255,255,255,0.8); margin: 8px 0 0 0;">${projectName}</p>
      </div>
      <div style="background: #f8fafc; padding: 32px; border-radius: 0 0 12px 12px;">
        <div style="background: white; padding: 24px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
          <p style="margin: 0 0 16px 0; font-size: 16px; line-height: 1.6;">${greeting}</p>
          <p style="margin: 0 0 16px 0; font-size: 16px; line-height: 1.6;">${intro}</p>
          ${summarySection}
          ${detailsSection}
          <div style="border-top: 1px solid #e2e8f0; padding-top: 24px; margin-top: 24px;">
            <p style="margin: 0; color: #64748b; font-size: 14px;">
              ${formattedFooter}
            </p>
          </div>
        </div>
        <p style="color: #64748b; font-size: 12px; margin-top: 24px; text-align: center;">
          ${unsubscribeText}
        </p>
      </div>
    </div>
  `;
}

serve(handler);
